builds:
  - binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: freebsd
        goarch: 'arm64'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

snapshot:
  name_template: "{{ .Version }}"
